# This file was generated by GoReleaser. DO NOT EDIT.
cask "odoo-work-cli" do
  name "odoo-work-cli"
  desc "CLI tool for managing Odoo 17 timesheets"
  homepage "https://github.com/seletz/odoo-work-cli"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "odoo-work-cli"

  on_macos do
    on_intel do
      url "https://github.com/seletz/odoo-work-cli/releases/download/v#{version}/odoo-work-cli-v#{version}-darwin-amd64.tar.gz"
      sha256 "770ec6889ab1b350afec0c449a5d0d56b40c4727eb265510a96149798771723d"
    end
    on_arm do
      url "https://github.com/seletz/odoo-work-cli/releases/download/v#{version}/odoo-work-cli-v#{version}-darwin-arm64.tar.gz"
      sha256 "9432d1ce7c7efe84df5db70becd658a132bb45165ca7327e8015c11d98abd3b9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/seletz/odoo-work-cli/releases/download/v#{version}/odoo-work-cli-v#{version}-linux-amd64.tar.gz"
      sha256 "b145989ea2dd9cb4282c12e69825cec19bb4385bd7f4024841e82e9cc3ccb3b0"
    end
    on_arm do
      url "https://github.com/seletz/odoo-work-cli/releases/download/v#{version}/odoo-work-cli-v#{version}-linux-arm64.tar.gz"
      sha256 "398c523fbb3547cbdc94e81d14a7e4029cb3c8f4e589f8436a8a5b54ca3b64ec"
    end
  end

  # No zap stanza required
end
