# This file was generated by GoReleaser. DO NOT EDIT.
cask "odoo-work-cli" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "ac68166a6845e6bb091b9d9dd3d545bc992026fa0b742f3429c6b68c67f23d91"
      url "https://github.com/seletz/odoo-work-cli/releases/download/v#{version}/odoo-work-cli-v#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "58699191caf815ee30e89b98266d638e9e8fe4cd7be9f3721c4acf95b4de81a2"
      url "https://github.com/seletz/odoo-work-cli/releases/download/v#{version}/odoo-work-cli-v#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "298fa47427470075d69f3d042c7a7c63a219cc3971bfb37c025755c71e6f6f6a"
      url "https://github.com/seletz/odoo-work-cli/releases/download/v#{version}/odoo-work-cli-v#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "f8de320cb93a87dda5656d54a3b0baf5e408ceedd9b80e6ab550f6549bea046c"
      url "https://github.com/seletz/odoo-work-cli/releases/download/v#{version}/odoo-work-cli-v#{version}-linux-arm64.tar.gz"
    end
  end

  name "odoo-work-cli"
  desc "CLI tool for managing Odoo 17 timesheets"
  homepage "https://github.com/seletz/odoo-work-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "odoo-work-cli"
  bash_completion "completions/odoo-work-cli.bash"
  fish_completion "completions/odoo-work-cli.fish"
  zsh_completion "completions/_odoo-work-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/odoo-work-cli"]
    end
  end

  # No zap stanza required

end
