# This file was generated by GoReleaser. DO NOT EDIT.
cask "odoo-work-cli" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/odoo-work-cli"]
    end
  end

  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "f1138c92a2ac23120f88f3b126d10d7dba04fe88a17b5ae89ac043a77b0788d3"
      url "https://github.com/seletz/odoo-work-cli/releases/download/v#{version}/odoo-work-cli-v#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "36a1237a02ac8fd6b3ede84c59a9c907fca68d5e231e841660ac541d2ae0e298"
      url "https://github.com/seletz/odoo-work-cli/releases/download/v#{version}/odoo-work-cli-v#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0a47fac75f79a2eb2abedfdfa264b48ca807f2603b60ea244b68a9f55f95f32c"
      url "https://github.com/seletz/odoo-work-cli/releases/download/v#{version}/odoo-work-cli-v#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "6b09d03bca74f6ca98a8df5720414fcc22b2ab8623fde2cfca92aa9aa12e00c8"
      url "https://github.com/seletz/odoo-work-cli/releases/download/v#{version}/odoo-work-cli-v#{version}-linux-amd64.tar.gz"
    end
  end

  name "odoo-work-cli"
  desc "CLI tool for managing Odoo 17 timesheets"
  homepage "https://github.com/seletz/odoo-work-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "odoo-work-cli"
  bash_completion "completions/odoo-work-cli.bash"
  fish_completion "completions/odoo-work-cli.fish"
  zsh_completion "completions/_odoo-work-cli"

  # No zap stanza required
end
