# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OdooWorkCli < Formula
  desc "CLI tool for managing Odoo 17 timesheets"
  homepage "https://github.com/seletz/odoo-work-cli"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/seletz/odoo-work-cli/releases/download/v0.2.2/odoo-work-cli-v0.2.2-darwin-amd64.tar.gz"
      sha256 "377f9977b24793e22d119d20667c6bd96760136437341f97b8a091a17e0a621c"

      define_method(:install) do
        bin.install "odoo-work-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/seletz/odoo-work-cli/releases/download/v0.2.2/odoo-work-cli-v0.2.2-darwin-arm64.tar.gz"
      sha256 "209f6d9a6c523c34cb4a6dbfc32b6da0e06c31fcffa590f95e85b688b36a1cf7"

      define_method(:install) do
        bin.install "odoo-work-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/seletz/odoo-work-cli/releases/download/v0.2.2/odoo-work-cli-v0.2.2-linux-amd64.tar.gz"
      sha256 "94792b5376c70b783b029ae0d8a3577028430229ea67ebdbcf9f3fd93aa6ddef"
      define_method(:install) do
        bin.install "odoo-work-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/seletz/odoo-work-cli/releases/download/v0.2.2/odoo-work-cli-v0.2.2-linux-arm64.tar.gz"
      sha256 "dd1ebb08fde04f6140219752e50f244d5d2da42956f5246772acf614a72f238a"
      define_method(:install) do
        bin.install "odoo-work-cli"
      end
    end
  end
end
